config/routes.rb
Rails.application.routes.draw do
  root 'issues#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :issues

  get 'reports/uat' => 'issues#uat'

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :issues
  validates :name, presence: true, uniqueness: true
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  belongs_to :domain
  belongs_to :status
  belongs_to :priority
  belongs_to :owner, class_name: 'User'
  belongs_to :assignee, class_name: 'User'

  validates :priority, presence: true
  validates :domain, presence: true
  validates :status, presence: true
  validates :owner, presence: true

  scope :text_search, -> (q) { q.present? ? basic_search(q) : all }
  scope :by_priority, -> (p) { p.present? ? where(priority: p) : all }
  scope :by_owner, -> (o) { o.present? ? where(owner_id: o) : all }
  scope :by_assignee, -> (a) { a.present? ? where(assignee_id: a) : all }
end

app/models/priority.rb
class Priority < ActiveRecord::Base
  has_many :issues
  validates :name, presence: true, uniqueness: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :issues
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :owned_issues, class_name: 'Issue', foreign_key: 'owner_id'
  has_many :assigned_issues, class_name: 'Issue', foreign_key: 'assignee_id'

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :require_login, raise: false

  def index
    @issues = Issue.text_search(params[:query])
                   .by_priority(params[:priority])
                   .by_owner(params[:owner])
                   .by_assignee(params[:assignee])
  end

  def show
    @issue = Issue.find(params[:id])
  end

  def new
    @issue = current_user.owned_issues.new
  end

  def create
    @issue = current_user.owned_issues.new(issue_params)
    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    @issue = Issue.find(params[:id])
    if @issue.update_attributes(issue_params)
      redirect_to @issue
    else
      render 'edit'
    end
  end

  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy
    redirect_to issues_path
  end

  def uat
    @priorities = Priority.all
    @statuses = Status.all
    @issues = Issue.all
  end

  private

  def issue_params
    params.require(:issue).permit(
      :observed_behaviour, :expected_behaviour, :priority_id, :domain_id,
      :assignee_id, :steps_to_reproduce, :additional_information, :status_id,
      :jira_reference
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/_fields.html.slim
= render 'shared/errors', object: f.object

div.small-12.medium-3.columns
  = f.label :domain_id
  = f.select :domain_id, Domain.order(:name).collect { |d| [d.name, d.id] }
div.small-12.medium-3.columns
  = f.label :status_id
  = f.select :status_id, Status.order(:id).collect { |s| [s.name, s.id] }
div.small-12.medium-3.columns
  = f.label :priority_id
  = f.select :priority_id, Priority.order(:id).collect { |p| [p.name, p.id] }
div.small-12.medium-3.columns
  = f.label :assignee_id
  = f.select :assignee_id, User.order(:name).collect { |u| [u.name, u.id] },
             include_blank: true
div.small-12.medium-6.columns
  = f.label :observed_behaviour
  = f.text_area :observed_behaviour, rows: 3
div.small-12.medium-6.columns
  = f.label :expected_behaviour
  = f.text_area :expected_behaviour, rows: 3
div.small-12.medium-6.columns
  = f.label :steps_to_reproduce
  = f.text_area :steps_to_reproduce, rows: 3
div.small-12.medium-6.columns
  = f.label :additional_information
  = f.text_area :additional_information, rows: 3
div.small-12.medium-6.columns
  = f.label :jira_reference
  = f.text_field :jira_reference

div.small-12.columns
  = f.submit class: 'success button'

app/views/issues/_issue.html.slim
tr
  td = link_to issue.id, issue_path(issue)
  td = issue.domain.name
  td = truncate issue.observed_behaviour, length: 75, separator: ' '
  td = truncate issue.expected_behaviour, length: 75, separator: ' '
  td = issue.status.name
  td = issue.priority.name
  td = issue.owner.name
  td = issue.assignee.try(:name)
  td = link_to 'edit', edit_issue_path(issue)
  td = link_to 'delete', issue_path(issue), method: :delete, 
               data: { confirm: 'Are you sure?' } 

app/views/issues/edit.html.slim
div.row
  div.small-12.columns
    h2 Edit Issue

    = form_for @issue do |f|
      = render 'fields', f: f

app/views/issues/index.html.slim
div.row
  div.small-12.columns
    h2 Issues
    
    = form_tag issues_path, method: :get
      div.small-12.medium-3.columns
        = text_field_tag 'query', params[:query], placeholder: 'Search'
      div.small-12.medium-2.columns
        = select_tag 'priority', 
                     options_for_select(Priority.order(:id).collect { |p| [p.name, p.id] }, params[:priority]),
                     include_blank: 'Priority'
      div.small-12.medium-3.columns
        = select_tag 'owner', 
                     options_for_select(User.order(:name).collect { |o| [o.name, o.id] }, params[:owner]),
                     include_blank: 'Owner'
      div.small-12.medium-3.columns
        = select_tag 'assignee', 
                     options_for_select(User.order(:name).collect { |a| [a.name, a.id] }, params[:assignee]),
                     include_blank: 'Assignee'
      div.small-12.medium-1.columns
        = submit_tag "Search", name: nil, class: 'button'
    
    table
      thead
        tr
          th ID
          th Domain
          th Observed Behaviour
          th Expected Behaviour
          th Status
          th Priority
          th Owner
          th Assignee
          th colspan="2" Actions
      tbody
        = render @issues
  
  div.small-12.medium-6.columns
    p Pagination
  
  nav.small-12.medium-6.columns
    ul.menu.align-right
      li = link_to 'New', new_issue_path, class: 'success button'

app/views/issues/new.html.slim
div.row
  div.small-12.columns
    h2 New Issue

    = form_for @issue do |f|
      = render 'fields', f: f

app/views/issues/show.html.slim
div.row
  div.small-12.columns
    h2 Issue
    
    div.small-12.medium-4.large-2.columns
      h5 Domain
      p = @issue.domain.name
    div.small-12.medium-4.large-2.columns
      h5 Status
      p = @issue.status.name
    div.small-12.medium-4.large-2.columns
      h5 Priority
      p = @issue.priority.name
    div.small-12.medium-4.large-2.columns
      h5 Owner
      p = @issue.owner.name
    div.small-12.medium-4.large-2.columns
      h5 Assignee
      p = @issue.assignee.try(:name)
    div.small-12.medium-4.large-2.columns
      h5 JIRA Reference
      p = @issue.jira_reference
    div.text-justify
      div.small-12.medium-6.columns
        h5 Observed Behaviour
        p = @issue.observed_behaviour
      div.small-12.medium-6.columns
        h5 Expected Behaviour
        p = @issue.expected_behaviour
      div.small-12.medium-6.columns
        h5 Steps To Reproduce
        p = @issue.steps_to_reproduce
      div.small-12.medium-6.columns
        h5 Additional Information
        p = @issue.additional_information    

      
  nav.small-12.columns
    ul.menu.align-right
      li = link_to 'Back', issues_path, class: 'button'
      li = link_to 'Edit', edit_issue_path, class: 'success button'
      li = link_to 'Delete', issue_path, method: :delete, 
                   data: { confirm: 'Are you sure?' },
                   class: 'alert button'
    

app/views/issues/uat.html.slim
div.row
  div.small-12.columns
    h2 UAT Report
    
    table
      thead
        tr
          th Priority | Status
          - @statuses.each do |status|
            th.text-center = status.name
          th.text-center Total
      tbody
        - @priorities.each do |priority|
          tr
            th.text-left = priority.name
            - @statuses.each do |status|
              td.text-center = status.issues.where(priority: priority).count
            td.text-center = priority.issues.count
        tr
          th.text-left Total
          - @statuses.each do |status|
            td.text-center
              = status.issues.count
          td.text-center = @issues.count

app/views/layouts/_header.html.slim
header.row
  div.small-12.columns
    h1.text-center MagnaLabs
  nav.small-12.medium-6.columns
    ul.menu
      li = link_to 'Issues', issues_path
      li = link_to 'UAT Report', reports_uat_path
  nav.small-12.medium-6.columns
    ul.menu.align-right
      - if signed_in?
        li = link_to 'Sign Out', session_path, method: :delete
        li.menu-text = current_user.email
      - else
        li = link_to 'Sign In', new_session_path
        li = link_to 'Sign Up', new_user_path

app/views/layouts/application.html.slim
doctype html
html lang='en'
  head
    meta charset='utf-8'
    meta name='viewport' content='width=device-width, initial-scale=1.0'

    title == content_for?(:title) ? yield(:title) : 'MagnaLabs'

    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tag

  body
    = render 'layouts/header'
    
    main
      = yield

app/views/shared/_errors.html.slim
- if object.errors.any?
	div
		p The form contains #{pluralize(object.errors.count, "error")}:
		ul
			- object.errors.full_messages.each do |msg|
				li = msg

app/views/users/new.html.slim
div.row
  div.small-12.medium-6.columns
    h2 Sign Up
    p Don't have an account? Sign up below!
    
    = form_for @user do |f|
      = render 'shared/errors', object: f.object
  
      div
        = f.label :email
        = f.email_field :email, require: true
      div
        = f.label :name
        = f.text_field :name, require: true
      div
        = f.label :password
        = f.password_field :password, require: true
      div
        = f.submit "Sign Up", class: 'success button'
        
  div.small-12.medium-6.columns
    h2 Sign In
    p Existing user? 
    = link_to 'Sign In Here!', new_session_path, class: 'button'